"""empty message

Revision ID: 44a6e9612205
Revises: 16b1c8ce331d
Create Date: 2020-04-17 15:41:09.477430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a6e9612205'
down_revision = '16b1c8ce331d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endorsement', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'endorsement', 'profile', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'endorsement', 'profile', ['giver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endorsement', type_='foreignkey')
    op.drop_constraint(None, 'endorsement', type_='foreignkey')
    op.drop_constraint(None, 'endorsement', type_='foreignkey')
    # ### end Alembic commands ###
